# Generated by Django 2.2.6 on 2019-10-06 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=100, unique=True)),
                ('ingredient_desc', models.CharField(max_length=1000)),
                ('ingredient_cost', models.IntegerField(default=0)),
                ('ingredient_unit_size', models.IntegerField(default=1)),
                ('is_fluid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apicbase.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100, unique=True)),
                ('recipe_desc', models.CharField(max_length=1000)),
                ('ingredients', models.ManyToManyField(to='apicbase.RecipeIngredient')),
            ],
        ),
    ]
