# Generated by Django 2.2.6 on 2019-10-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicbase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingredient_name',
            new_name='ingredient',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='apicbase.RecipeIngredient', to='apicbase.Ingredient'),
        ),
    ]
